version: '3'
services:
  postgres:
    image: postgres:13.4
    volumes:
      - test_db_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: test_db
volumes:
  test_db_data: {}